export const fruits = [
  { id: "apple", text: "apple" },
  { id: "apricot", text: "apricot" },
  { id: "avocado", text: "avocado" },
  { id: "banana", text: "banana" },
  { id: "bell pepper", text: "bell pepper" },
  { id: "bilberry", text: "bilberry" },
  { id: "blackberry", text: "blackberry" },
  { id: "blackcurrant", text: "blackcurrant" },
  { id: "blood orange", text: "blood orange" },
  { id: "blueberry", text: "blueberry" },
  { id: "boysenberry", text: "boysenberry" },
  { id: "breadfruit", text: "breadfruit" },
  { id: "canary melon", text: "canary melon" },
  { id: "cantaloupe", text: "cantaloupe" },
  { id: "cherimoya", text: "cherimoya" },
  { id: "cherry", text: "cherry" },
  { id: "chili pepper", text: "chili pepper" },
  { id: "clementine", text: "clementine" },
  { id: "cloudberry", text: "cloudberry" },
  { id: "coconut", text: "coconut" },
  { id: "cranberry", text: "cranberry" },
  { id: "currant", text: "currant" },
  { id: "damson", text: "damson" },
  { id: "date", text: "date" },
  { id: "dragonfruit", text: "dragonfruit" },
  { id: "durian", text: "durian" },
  { id: "eggplant", text: "eggplant" },
  { id: "elderberry", text: "elderberry" },
  { id: "feijoa", text: "feijoa" },
  { id: "fig", text: "fig" },
  { id: "goji berry", text: "goji berry" },
  { id: "gooseberry", text: "gooseberry" },
  { id: "grape", text: "grape" },
  { id: "grapefruit", text: "grapefruit" },
  { id: "guava", text: "guava" },
  { id: "honeydew", text: "honeydew" },
  { id: "huckleberry", text: "huckleberry" },
  { id: "jackfruit", text: "jackfruit" },
  { id: "jambul", text: "jambul" },
  { id: "jujube", text: "jujube" },
  { id: "kiwi fruit", text: "kiwi fruit" },
  { id: "kumquat", text: "kumquat" },
  { id: "lemon", text: "lemon" },
  { id: "lime", text: "lime" },
  { id: "loquat", text: "loquat" },
  { id: "lychee", text: "lychee" },
  { id: "mandarine", text: "mandarine" },
  { id: "mango", text: "mango" },
  { id: "mulberry", text: "mulberry" },
  { id: "nectarine", text: "nectarine" },
  { id: "nut", text: "nut" },
  { id: "olive", text: "olive" },
  { id: "orange", text: "orange" },
  { id: "pamelo", text: "pamelo" },
  { id: "papaya", text: "papaya" },
  { id: "passionfruit", text: "passionfruit" },
  { id: "peach", text: "peach" },
  { id: "pear", text: "pear" },
  { id: "persimmon", text: "persimmon" },
  { id: "physalis", text: "physalis" },
  { id: "pineapple", text: "pineapple" },
  { id: "plum", text: "plum" },
  { id: "pomegranate", text: "pomegranate" },
  { id: "pomelo", text: "pomelo" },
  { id: "purple mangosteen", text: "purple mangosteen" },
  { id: "quince", text: "quince" },
  { id: "raisin", text: "raisin" },
  { id: "rambutan", text: "rambutan" },
  { id: "raspberry", text: "raspberry" },
  { id: "redcurrant", text: "redcurrant" },
  { id: "rock melon", text: "rock melon" },
  { id: "salal berry", text: "salal berry" },
  { id: "satsuma", text: "satsuma" },
  { id: "star fruit", text: "star fruit" },
  { id: "strawberry", text: "strawberry" },
  { id: "tamarillo", text: "tamarillo" },
  { id: "tangerine", text: "tangerine" },
  { id: "tomato", text: "tomato" },
  { id: "ugli fruit", text: "ugli fruit" },
  { id: "watermelon", text: "watermelon" }
];

export const vegetables = [
  { id: "acorn squash", text: "acorn squash" },
  { id: "alfalfa sprout", text: "alfalfa sprout" },
  { id: "amaranth", text: "amaranth" },
  { id: "anise", text: "anise" },
  { id: "artichoke", text: "artichoke" },
  { id: "arugula", text: "arugula" },
  { id: "asparagus", text: "asparagus" },
  { id: "aubergine", text: "aubergine" },
  { id: "azuki bean", text: "azuki bean" },
  { id: "banana squash", text: "banana squash" },
  { id: "basil", text: "basil" },
  { id: "bean sprout", text: "bean sprout" },
  { id: "beet", text: "beet" },
  { id: "black bean", text: "black bean" },
  { id: "black-eyed pea", text: "black-eyed pea" },
  { id: "bok choy", text: "bok choy" },
  { id: "borlotti bean", text: "borlotti bean" },
  { id: "broad beans", text: "broad beans" },
  { id: "broccoflower", text: "broccoflower" },
  { id: "broccoli", text: "broccoli" },
  { id: "brussels sprout", text: "brussels sprout" },
  { id: "butternut squash", text: "butternut squash" },
  { id: "cabbage", text: "cabbage" },
  { id: "calabrese", text: "calabrese" },
  { id: "caraway", text: "caraway" },
  { id: "carrot", text: "carrot" },
  { id: "cauliflower", text: "cauliflower" },
  { id: "cayenne pepper", text: "cayenne pepper" },
  { id: "celeriac", text: "celeriac" },
  { id: "celery", text: "celery" },
  { id: "chamomile", text: "chamomile" },
  { id: "chard", text: "chard" },
  { id: "chayote", text: "chayote" },
  { id: "chickpea", text: "chickpea" },
  { id: "chives", text: "chives" },
  { id: "cilantro", text: "cilantro" },
  { id: "collard green", text: "collard green" },
  { id: "corn", text: "corn" },
  { id: "corn salad", text: "corn salad" },
  { id: "courgette", text: "courgette" },
  { id: "cucumber", text: "cucumber" },
  { id: "daikon", text: "daikon" },
  { id: "delicata", text: "delicata" },
  { id: "dill", text: "dill" },
  { id: "eggplant", text: "eggplant" },
  { id: "endive", text: "endive" },
  { id: "fennel", text: "fennel" },
  { id: "ftextdlehead", text: "ftextdlehead" },
  { id: "frisee", text: "frisee" },
  { id: "garlic", text: "garlic" },
  { id: "gem squash", text: "gem squash" },
  { id: "ginger", text: "ginger" },
  { id: "green bean", text: "green bean" },
  { id: "green pepper", text: "green pepper" },
  { id: "habanero", text: "habanero" },
  { id: "herbs and spice", text: "herbs and spice" },
  { id: "horseradish", text: "horseradish" },
  { id: "hubbard squash", text: "hubbard squash" },
  { id: "jalapeno", text: "jalapeno" },
  { id: "jerusalem artichoke", text: "jerusalem artichoke" },
  { id: "jicama", text: "jicama" },
  { id: "kale", text: "kale" },
  { id: "ktextney bean", text: "ktextney bean" },
  { id: "kohlrabi", text: "kohlrabi" },
  { id: "lavender", text: "lavender" },
  { id: "leek ", text: "leek " },
  { id: "legume", text: "legume" },
  { id: "lemon grass", text: "lemon grass" },
  { id: "lentils", text: "lentils" },
  { id: "lettuce", text: "lettuce" },
  { id: "lima bean", text: "lima bean" },
  { id: "mamey", text: "mamey" },
  { id: "mangetout", text: "mangetout" },
  { id: "marjoram", text: "marjoram" },
  { id: "mung bean", text: "mung bean" },
  { id: "mushroom", text: "mushroom" },
  { id: "mustard green", text: "mustard green" },
  { id: "navy bean", text: "navy bean" },
  { id: "new zealand spinach", text: "new zealand spinach" },
  { id: "nopale", text: "nopale" },
  { id: "okra", text: "okra" },
  { id: "onion", text: "onion" },
  { id: "oregano", text: "oregano" },
  { id: "paprika", text: "paprika" },
  { id: "parsley", text: "parsley" },
  { id: "parsnip", text: "parsnip" },
  { id: "patty pan", text: "patty pan" },
  { id: "pea", text: "pea" },
  { id: "pinto bean", text: "pinto bean" },
  { id: "potato", text: "potato" },
  { id: "pumpkin", text: "pumpkin" },
  { id: "radicchio", text: "radicchio" },
  { id: "radish", text: "radish" },
  { id: "rhubarb", text: "rhubarb" },
  { id: "rosemary", text: "rosemary" },
  { id: "runner bean", text: "runner bean" },
  { id: "rutabaga", text: "rutabaga" },
  { id: "sage", text: "sage" },
  { id: "scallion", text: "scallion" },
  { id: "shallot", text: "shallot" },
  { id: "skirret", text: "skirret" },
  { id: "snap pea", text: "snap pea" },
  { id: "soy bean", text: "soy bean" },
  { id: "spaghetti squash", text: "spaghetti squash" },
  { id: "spinach", text: "spinach" },
  { id: "squash ", text: "squash " },
  { id: "sweet potato", text: "sweet potato" },
  { id: "tabasco pepper", text: "tabasco pepper" },
  { id: "taro", text: "taro" },
  { id: "tat soi", text: "tat soi" },
  { id: "thyme", text: "thyme" },
  { id: "topinambur", text: "topinambur" },
  { id: "tubers", text: "tubers" },
  { id: "turnip", text: "turnip" },
  { id: "wasabi", text: "wasabi" },
  { id: "water chestnut", text: "water chestnut" },
  { id: "watercress", text: "watercress" },
  { id: "white radish", text: "white radish" },
  { id: "yam", text: "yam" },
  { id: "zucchini ", text: "zucchini " }
];
